### ISSUE TITLE
Use COBS on existing index

### ISSUE THREAD

**Issue by davidmaimoun** [iqbal-lab-org/cobs#10]
Hi,
I would like to use the created index from:
http://ftp.ebi.ac.uk/pub/databases/ENA2018-bacteria-661k/
To run a query (Salmonella's sequences) with COBS
Could you tell me which folder I need to download (sorry I am very new in the field) ?

Thank you

**Comment by leoisl** [comment]
Hello,

To query the 661k COBS index you will have to download the full COBS index: http://ftp.ebi.ac.uk/pub/databases/ENA2018-bacteria-661k/661k.cobs_compact and run your query against it

**Comment by davidmaimoun** [comment]
Thank you very much
