### ISSUE TITLE
Query reads from fastq.gz files

### ISSUE THREAD

**Issue by jermp** [iqbal-lab-org/cobs#20]
Hi,
it seems queries are only supported when stored in fasta format.
Do you have any plan to enable query from reads in fastq.gz files?

Thanks,
-Giulio

**Comment by iqbal-lab** [comment]
Hi Giulio!
Was not really planning to do this,  do you have a use-case not covered by taxonomic assigners or mappers? Sorry slow reply, on holiday, back next week

**Comment by leoisl** [comment]
Hey Giulio, Zam,
this fix is actually quite simple, has been implemented in this branch: https://github.com/iqbal-lab-org/cobs/tree/fix/20 . Could you please try @jermp ? It worked on the integration tests, if it works for you as well, I will PR and merge it to main.
Cheers

**Comment by jermp** [comment]
Hi Zamin and @leoisl, the patch works. Thanks!
